global using ERP.Domain.Entities;
global using ERP.Domain.Enums;
global using ERP.Domain.Common;
global using ERP.Application.Interfaces.Repositories;
global using ERP.Infrastructure.Data;
global using ERP.Infrastructure.Repositories;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.AspNetCore.Hosting;
global using ErpDbContext = ERP.Infrastructure.Data.ApplicationDbContext;
